### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by Simn** [Aidan63/haxe#121]
```haxe
import hxcoro.ds.Channel;
import haxe.Timer;
import hxcoro.CoroRun;
import hxcoro.Coro.*;

function main() {
	final startTime = Timer.stamp();
	var aggregateValue = 0;
	CoroRun.runScoped(node -> {
		final channel = new Channel();
		final numTasks = 100000;
		var completedWriters = 0;
		var completedReaders = 0;
		// set up writers
		for (_ in 0...numTasks) {
			node.async(_ -> {
				delay(Std.random(1000));
				channel.write(1);
				completedWriters++;
			});
		}
		// set up readers
		for (_ in 0...numTasks) {
			node.async(_ -> {
				delay(Std.random(1000));
				aggregateValue += channel.read();
				completedReaders++;
			});
		}
		node.awaitChildren();
		trace("done", completedWriters, completedReaders);
	});
	trace('done after ${Timer.stamp() - startTime} seconds, aggregate value is $aggregateValue');
}
```

Compiling this to JS or C++ makes it run for a few seconds before crashing. JS tells me it's out of memory, so I assume that's what happens on C++ as well. I think we're still holding onto all our tasks even after they completed, but I haven't been able to figure out where they're still referenced.

**Comment by Simn** [comment]
Hmm, it's the double buffer:

<img width="1645" alt="Image" src="https://github.com/user-attachments/assets/dfba4011-08a8-40cf-8ede-78310e6ff01f" />

Removing the `schedule` call from `CoroTask.async` indeed gives a much better memory profile and makes JS work. C++ still crashes though.

Part of the problem with regards to JVM is that its `Array.resize` method doesn't actually unset any values, it just updates the length. So this isn't the best target to profile this on.

**Comment by Aidan63** [comment]
When I added that I was a bit concerned that the buffer is only wiped just before it's returned. That means if it's a long time between flip calls it could be a long time before it's resized to zero (which is when references would be lost / eligable for collection). Not sure if thats part of the problem here.

**Comment by Simn** [comment]
I thought that this might be good:

```haxe
			final events = zeroEvents.flip();
			for (index => event in events) {
				events[index] = null;
				event();
			}
```

But it doesn't seem to change much at all.

**Comment by Simn** [comment]
I did some heap inspection on this:

```haxe
import hxcoro.ds.Channel;
import haxe.Timer;
import hxcoro.CoroRun;
import hxcoro.Coro.*;

function main() {
	final startTime = Timer.stamp();
	var aggregateValue = 0;
	CoroRun.runScoped(node -> {
		final channel = new Channel();
		final numTasks = 100;
		var completedWriters = 0;
		var completedReaders = 0;
		final numTasksHalved = Std.int(numTasks / 2);
		// set up writers
		for (_ in 0...numTasks) {
			node.async(_ -> {
				delay(Std.random(1000));
				channel.write(1);
				completedWriters++;
			});
		}
		// set up readers
		for (_ in 0...numTasks) {
			node.async(_ -> {
				delay(Std.random(1000));
				while (aggregateValue == numTasksHalved) {
					yield();
				}
				aggregateValue += channel.read();
				completedReaders++;
			});
		}
		while (aggregateValue != numTasksHalved) {
			yield();
		}
		yield();
		trace("done", completedWriters, completedReaders);
		node.awaitChildren();
	});
	trace('done after ${Timer.stamp() - startTime} seconds, aggregate value is $aggregateValue');
}
```

It stops the readers at the halfway point, which then causes the whole program to hang so I can inspect the heap. And the heap looks like it should look:

<img width="814" alt="Image" src="https://github.com/user-attachments/assets/32d5db37-5145-4f5a-8921-8dd8cd2040fd" />

97 CoroChildTask instances is exactly right: it's the 50 hanging readers and 47 hanging writers because 3 of them made it onto the channel's `writeQueue`. So the good news is that we're not leaking tasks.

I think this must mean that something causes terrible short-term memory spikes which causes out-of-memory problems. I'm not sure what it could be though because everything here is supposed to be pretty "flat" memory-wise. I could only see this being a problem if we had very deep continuation chains that aren't unset until the root is reached, but I don't think we have it. It is probably still a good idea to null things like `BaseContinuation.completion` after resuming it, although I also don't know why a resumed `BaseContinuation` would still hang around somewhere.

**Comment by Simn** [comment]
VS tells me this isn't actually a memory problem, at least not explicitly. The program slowly goes to 2.5 GB memory usage and then gets an access violation on null. It could be some hxcpp GC problem, which would at least explain why we have to push for high memory usage before it triggers. It could of course also be a boring old null value access, but that seems likely if C++ is the only target where it happens.

**Comment by Aidan63** [comment]
Does that program have the option to see the retention paths of individual instances? I've used Jetbrain's dotMemory before for C# stuff which allows you to drill down to individual objects and see whats keeping them around. Jetbrains do all sorts of java stuff so they've probably got something which does the same.

**Comment by Aidan63** [comment]
I also see the access violation around 2.5GB, I think thats just the GC limits kicking in. It's hitting a debug trap in the GCs allocator for when it's ran out of memory.

![Image](https://github.com/user-attachments/assets/97dacff7-9ce9-4ec3-a923-27f14427319e)

That `DebuggerTrap` function is where it deferences a null pointer to cause a debugger to break.

**Comment by Simn** [comment]
Hmm, but where does that limitation come from? This amount of memory should not be a problem in a 64bit program.

**Comment by Aidan63** [comment]
The number of "blocks" the GC can track, without the big blocks define it uses 15 bits to store the block ID. So once you've allocated enough blocks to exceed that limit allocation will fail. In this case it's trying to allocate more blocks as all the other ones are full of live objects so there's no space to fit the object which wants to be allocated (my knowledge of hxcpps gc internals are not great, so that this with a grain of salt).

**Comment by Aidan63** [comment]
I took another look at this since there have been many changes to both channels and the event loop since this issue was opened. The good news is that I can't recreate the out of memory issue anymore, the bad news is that there does seem to be a problem with out event loop when it's under heavy contention.

This is the sample I'm now working with.

```haxe
import hxcoro.ds.channels.Channel;
import hxcoro.ds.Out;
import haxe.Timer;
import hxcoro.CoroRun;
import hxcoro.Coro.*;

function main() {
	final startTime = Timer.stamp();
	var aggregateValue = 0;
	CoroRun.runScoped(node -> {
		final channel = Channel.createBounded({ size: 10 });
		final numTasks = 1000;

		// set up writers
		var count = 0;
		for (_ in 0...numTasks) {
			node.async(_ -> {
				delay(Std.random(1000));

				channel.writer.write(1);
				
				if (++count == numTasks) {
					channel.writer.close();
				}
			});
		}

		// set up readers
		for (_ in 0...numTasks) {
			node.async(_ -> {
				final o = new Out();

				while (channel.reader.waitForRead()) {
					if (channel.reader.tryRead(o)) {
						aggregateValue += o.get();
					}
					else {
						continue;
					}

					delay(Std.random(1000));
				}
			});
		}

		node.awaitChildren();

		trace("done");
	});
	trace('done after ${Timer.stamp() - startTime} seconds, aggregate value is $aggregateValue');
}
```

When `numTasks` is very small, every thing works fine, but if you change it to 100000 then the program seems to hang. Peppering some traces around show that all writer tasks hit that `delay` but they never get woken up so nothing is ever written to the channel. Then things start to get a bit mad. If you change that `Std.random(1000)` in the writers to just `1000` it all seems to work fine! The writers get woken up, write a value to the channel, and the readers pick them up. You can also get it to work with the random call if you place a `yield` inside the for loop and just before the `node.async` call.

Not really dug into it but something weirds going on with the event loop, this occurs on cpp, jvm, and js (not tested others), so I don't think it's a lock related dead lock.

**Comment by Aidan63** [comment]
Tried using the nodejs scheduler (libuv) and that does work with when `taskNum` is 100000, although it is fairly sluggish.

```haxe
import hxcoro.ds.channels.Channel;
import hxcoro.ds.Out;
import haxe.Timer;
import hxcoro.CoroRun;
import hxcoro.Coro.*;
import haxe.coro.Coroutine;
import haxe.coro.context.Context;
import haxe.coro.context.IElement;
import haxe.coro.schedulers.EventLoopScheduler;
import hxcoro.task.ICoroTask;
import hxcoro.task.CoroTask;
import hxcoro.task.StartableCoroTask;
import hxcoro.task.NodeLambda;
import haxe.Timer;
import haxe.coro.cancellation.CancellationToken;
import haxe.Exception;
import haxe.coro.Coroutine;
import hxcoro.Coro.*;
import haxe.coro.context.Context;
import haxe.coro.schedulers.Scheduler;
import haxe.coro.IContinuation;
import haxe.coro.schedulers.IScheduleObject;
import haxe.exceptions.CancellationException;

private class JsScheduler extends Scheduler {
	public function new() {
		super();
	}

	public function schedule(ms:haxe.Int64, func:() -> Void) {
		haxe.Timer.delay(func, haxe.Int64.toInt(ms));
		return null; // what to return here?
	}

	public function scheduleObject(obj:IScheduleObject) {
		haxe.Timer.delay(() -> obj.onSchedule(), 0);
	}

	public function now() {
		return Timer.milliseconds();
	}
}

function main() {
	final startTime = Timer.stamp();
	var aggregateValue = 0;

	final schedulerComponent = new JsScheduler();
	final scope = new CoroTask(Context.create(schedulerComponent), CoroTask.CoroScopeStrategy);
	scope.runNodeLambda(node -> {
		final channel = Channel.createBounded({ size: 10 });
		final numTasks = 10000;

		// set up writers
		var count = 0;
		for (_ in 0...numTasks) {
			node.async(_ -> {
				delay(Std.random(1000));

				trace('woke up');

				channel.writer.write(1);

				trace(count);
				
				if (++count == numTasks) {
					channel.writer.close();
				}
			});
		}

		// set up readers
		for (_ in 0...numTasks) {
			node.async(_ -> {
				final o = new Out();

				while (channel.reader.waitForRead()) {
					if (channel.reader.tryRead(o)) {
						aggregateValue += o.get();
					}
					else {
						continue;
					}

					delay(Std.random(1000));
				}
			});
		}

		node.awaitChildren();

		trace("done");
		trace('done after ${Timer.stamp() - startTime} seconds, aggregate value is $aggregateValue');
	});
}
```

Either way it seems our event loop can't handle heavy loads and needs some work.

**Comment by Simn** [comment]
https://github.com/Aidan63/haxe/commit/005a355993cacfc468cec39bcc3207c4c0c96ef7 removed some of the optimizations in the scheduler, specifically the one that would walk the linked list from both ends that I originally added in https://github.com/Aidan63/haxe/commit/17e5ddf9955d94bb1f9875021791b3b96d6d39d8. I think I added that for the pathological case where many elements are added at the end of the list, which I came across here. I also seem to remember talking about this in some issue but I can't find that right now.

**Comment by Simn** [comment]
I've tested with `numTasks = 7500` before and after https://github.com/Aidan63/haxe/commit/005a355993cacfc468cec39bcc3207c4c0c96ef7. Before it would consistently terminate with a run-time of around 8 seconds, after it either terminates in 5.5 seconds or hangs.

There's definitely a `futureMutex.release();` missing at the loop exit, but that's not the real problem here because it still hangs with that.

Another thing that looks suspicious is the `if (event.runTime >= currentFirst.runTime && currentFirst.next.runTime > event.runTime)` condition because I think `currentFirst.next` could be `null`, but I don't know why we're not just getting a null access error here.

**Comment by Simn** [comment]
Never mind, I think the only reason it didn't hang before https://github.com/Aidan63/haxe/commit/005a355993cacfc468cec39bcc3207c4c0c96ef7 is that there was a bug in the scheduler that messed everything up. After fixing that bug I get the same hanging behavior as with the current scheduler.

... which makes me doubt that this is a scheduler problem in the first place. 

Edit: Of note: if I try often enough I can get the hang even with `numTasks = 500` and `Std.random(10)`, so this isn't about heavy load at all.

**Comment by Simn** [comment]
We can reproduce this without any randomness by putting it in a loop with a smallish `numTasks`:

```haxe
import hxcoro.ds.channels.Channel;
import hxcoro.ds.Out;
import haxe.Timer;
import hxcoro.CoroRun;
import hxcoro.Coro.*;

function main() {
	for (i in 0...100) {
		final startTime = Timer.stamp();
		trace("start " + i);
		var aggregateValue = 0;
		CoroRun.runScoped(node -> {
			final channel = Channel.createBounded({size: 10});
			final numTasks = 500;

			// set up writers
			var count = 0;
			for (_ in 0...numTasks) {
				node.async(_ -> {
					delay(1);

					channel.writer.write(1);

					if (++count == numTasks) {
						channel.writer.close();
					}
				});
			}

			// set up readers
			for (_ in 0...numTasks) {
				node.async(_ -> {
					final o = new Out();

					while (channel.reader.waitForRead()) {
						if (channel.reader.tryRead(o)) {
							aggregateValue += o.get();
						} else {
							continue;
						}

						delay(1);
					}
				});
			}

			node.awaitChildren();
		});
		trace('done after ${Timer.stamp() - startTime} seconds, aggregate value is $aggregateValue');
	}
}
```

It seems to always terminate with `delay(0)`, but `delay(1)` causes it to hang. This doesn't appear to be about the `zeroMutex` optimization in the scheduler because commenting that out still doesn't make `delay(0)` hang.

I don't know why this isn't deterministic.

**Comment by Aidan63** [comment]
I've just tried out that sample and with `delay(1)` on the js target I've never seen it run to completion. It always eventually hangs and stepping through with a debugger seems to show that there are no events in the scheduler...

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/1bfb6b42-e94d-43f9-af98-a91b5aa4f30e" />

First and last are null, and the zero events buffer is completely empty, but it's only done 19 iterations and is now "hanging" (pumping the event loop forever).

Interestingly I've ran this same code nearly 10 times on the cpp target and it completes each time... I've not tried other targets yet.

**Comment by Aidan63** [comment]
|target|state|
|-|-|
|js|hangs|
|jvm|hangs|
|cpp|completes|
|hl|completes|
|eval|completes|
|neko|completes|
|python|completes|

I don't know what this tells us other than something weird is going on. Might just be a coincidence but js and jvm complete each iteration very quickly (less than 0.1s) where as all the targets which complete take much longer (> 1s).

**Comment by Simn** [comment]
I just tested it on C++ and found that with `-debug` it runs (agonizingly slowly) to completion, but in release mode it hangs too.

**Comment by Aidan63** [comment]
Right, I had the debug flag in my build.hxml. Just tried cpp and hl without the debug flag and I can then get them to hang as well (and each iteration up to the hang is much faster).

**Comment by Aidan63** [comment]
Put the cpp exe in windbg so I can do a trace recording and it doesn't seem to hang while running from there (but each iteration takes an age).

<img width="1202" height="580" alt="Image" src="https://github.com/user-attachments/assets/fb3f0eab-b036-4a80-bb43-b2c37a53b887" />

But running that same exe through vscodes terminal (no debugger attached) it does just seem to hang...

<img width="618" height="71" alt="Image" src="https://github.com/user-attachments/assets/5667387b-5e9e-4abd-803b-b1cd610281ac" />

WTF

**Comment by Simn** [comment]
This must be some collision problem that is more likely to occur with tighter timing. The only root cause of the non-determinism I can think of is `Timer.milliseconds()` having the same value for two different things, which then never happens in slower runs.

**Comment by Aidan63** [comment]
I had another attempt to get to the bottom of this, thought I'd play around with a different structure for holding the scheduled events and implemented a minimum heap instead of a linked list. However... zero change, that sample still hangs.

After further poking and prodding I found that if I change the `scheduleObject` function to immediately call it's object `obj.onSchedule();` it all works fine, even without the minimum heap change. I have yet to figure out what this means...

**Comment by Aidan63** [comment]
On an unrelated note this minimum heap seems to speed the event loop up a nice amount.

With minimum heap

<img width="710" height="209" alt="Image" src="https://github.com/user-attachments/assets/78046d5a-59ba-4076-93e2-b59c67c4622c" />

Without minimum heap

<img width="667" height="208" alt="Image" src="https://github.com/user-attachments/assets/f1f918a5-6d50-463c-b380-87954efecf8d" />

Both on JVM without debug and `numTasks` set to 10000.

**Comment by Simn** [comment]
Could you share your  implementation? I'm quite curious about this. I remember considering a heap data structure for this as well but then dismissed it, but I don't remember why.

**Comment by Aidan63** [comment]
I've just pushed a heap-loop branch with that the minimum heap and the immediate calling of the `ScheduleObject`, some things to note.

- I have not implemented closing handles yet, so that throws an exception. I have not ran the test suite yet due to this.
- I don't know what happens order wise if you add two items of the same due time to the heap. Do we want to maintain FIFO when times collide?
- This is a extremely naive array based implementation, I'm sure there's many more improvements which could be done.

**Comment by Aidan63** [comment]
~~Ah, I've also realised there's no mutexes with this heap, that might explain it...~~ 

No, never mind, the future mutex is still there.

**Comment by Simn** [comment]
Another way to fix this is moving the call to `runZeroEvents` into the loop like so:

```haxe
	public function run() {
		final currentTime = now();
		while (true) {
			runZeroEvents();
			futureMutex.acquire();

			if (first == null) {
				last = null;
				break;
			}
			if (first.runTime <= currentTime) {
				final toRun = first;
				first = first.next;
				if (first != null) {
					first.previous = null;
				}
				futureMutex.release();
				toRun.run();
				futureMutex.acquire();
			} else {
				break;
			}
		}
		futureMutex.release();
	}
```

Thinking about this, if our `currentTime` is 4 and we have events to run at 1 and 3, and the event at 1 schedules another zero-event 1+, in the current implementation we would run `1, 3, 1+` while in this changed version we run `1, 1+, 3` which looks more correct.

This still doesn't seem quite correct though because any zero-event that schedules another zero-event would have the same problem as we won't look at the scheduled event until the next loop iteration.

I'm starting to think that our separation of zero-events and other events is a bit flawed...

**Comment by Simn** [comment]
Now I'm not sure anymore if my interpretation actually makes sense. There seem to be two ways of thinking about it:

1. The current time is the time we start working on the event queue. In this case any (zero-)delay would be scheduled for the future. In my previous example, execution order should then be `1, 3, 1+`.
2. The current time is the time of the current event. This is how the virtual scheduler interprets this, and delays are then relative to that starting time, giving us the `1, 1+, 3` order I was mentioning.

With my latest change all zero-delays in particular work like in the second case, but any other delays would not: if the event at timestep 1 has a `delay(1)` then the order would still be `1, 3, 2` in the real scheduler, whereas with the virtual scheduler it would execute as `1, 2, 3`.

I don't know what's correct here.

**Comment by Aidan63** [comment]
Since I took all this scheduler stuff from C#'s Rx.NET library I decided to see how it handles this.

```C#
var s = new TestScheduler();

s.Schedule(TimeSpan.FromSeconds(1), () =>
{
    Console.WriteLine($"1 at {s.Now.Ticks}");

    s.Schedule(() => Console.WriteLine($"1+ at {s.Now.Ticks}"));
});

s.Schedule(TimeSpan.FromSeconds(3), () => Console.WriteLine($"3 at {s.Now.Ticks}"));
s.Start();
```

`TestScheduler` is a virtual time scheduler and `Start` is a convenience function to run all the scheduled events, saves you needing to do `AdvanceBy` / `AdvanceTo` with the right time. With this code we get

```
1 at 10000000
1+ at 10000001
3 at 30000000
```

I also tried with a "real" scheduler, `CurrentThreadScheduler.Instance` and got the same result.

```
1 at 639029599895360589
1+ at 639029599895471400
3 at 639029599925492479
```

**Comment by Simn** [comment]
Ah, so it's working with ticks that auto-increment? That's quite different from we're doing and would explain why a `while(true) yield()` loop doesn't just hang in some cases such as this:

```haxe
import hxcoro.schedulers.VirtualTimeScheduler;
import hxcoro.CoroRun;
import hxcoro.Coro.*;

function main() {
	final scheduler = new VirtualTimeScheduler();
	final task = CoroRun.with(scheduler).create(node -> {
		final child = node.async(node -> {
			while (true) {
				yield();
			}
		});

		trace("delaying 500");
		delay(500);
		trace("delayed 500");

		child.cancel();
	});

	task.start();

	trace("-->   1");
	scheduler.advanceBy(1);
	trace("--> 500");
	scheduler.advanceBy(499);
}
```

This works fine with `advanceBy(500)`, but with just a single step advance we end up with the `yield()` continuously rescheduling itself and nothing else happening. It also hangs with `advanceBy(500)` if we change `scheduleObject` like so:

```haxe
	public function scheduleObject(obj:IScheduleObject) {
		final event = new ScheduledEvent(closeClosure, () -> obj.onSchedule(), now());
		addEvent(event);
	}
```

The only reason this works at all is a little quirk in `virtualRun`: it executes all zero-events via `runZeroEvents()` and then a single element from the real list, if its time matches.

**Comment by Aidan63** [comment]
The Rx.NET scheduler works in absolute time internally, it's `Now` property returns a `DateTimeOffset`. You then have overloads for scheduling work at an absolute `DateTimeOffset` or a `TimeSpan` relative to `Now`. There is also a dedicated overload of `schedule` which takes no time and just says it schedules it for execution as soon as possible, this would be the equivilent of our zero events I guess.

I originally wanted to do this for ours as well but the Haxe Date api is object based and it seemed too expensive to use `Date.now` since it would allocate and object and we'd be calling that a lot. C# date times work differently, it stores absolute times as a 64bit int of "ticks".

> Time values are measured in 100-nanosecond units called ticks. A particular date is the number of ticks since 12:00 midnight, January 1, 0001 A.D. (C.E.) in the [GregorianCalendar](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.gregoriancalendar) calendar.

Core Rx.NET scheduler interface

```C#
public interface IScheduler
{
    DateTimeOffset Now { get; }

    IDisposable Schedule<TState>(TState state, Func<IScheduler, TState, IDisposable> action);
    IDisposable Schedule<TState>(TState state, TimeSpan dueTime, Func<IScheduler, TState, IDisposable> action);
    IDisposable Schedule<TState>(TState state, DateTimeOffset dueTime, Func<IScheduler, TState, IDisposable> action);
}
```

**Comment by Simn** [comment]
The part I don't understand is how it went from `10000000` to `10000001`. To me that suggests that the tick value must have incremented, which is not what we're doing with our `currentTime`. And I think it's necessary because otherwise we'll never get out of a `while(true) yield()`.

**Comment by Aidan63** [comment]
It seems like `TestScheduler` overrides `ScheduleAbsolute` and adds 1 to the current clock if it's not in the future.

```C#
        public override IDisposable ScheduleAbsolute<TState>(TState state, long dueTime, Func<IScheduler, TState, IDisposable> action)
        {
            if (dueTime <= Clock)
            {
                dueTime = Clock + 1;
            }

            return base.ScheduleAbsolute(state, dueTime, action);
        }
```

https://github.com/dotnet/reactive/blob/main/Rx.NET/Source/src/Microsoft.Reactive.Testing/TestScheduler.cs#L31

**Comment by Simn** [comment]
After some more investigation I've concluded that we should focus on your minimum heap approach because it's the most promising I've seen so far. I have updated that branch to properly support `scheduleObject` by attaching to the minimum heap element if its due-time matches. This seems appropriate because it groups all these zero-events in a single `ScheduledEvent`, which is what we want.

The heap solution also runs into the `while(true) yield()` problem in the virtual scheduler, for which I don't have a solution yet. I've changed the related tests to use `delay(1)` instead which I suppose is fair enough.

As you pointed out, we still need to implement cancellation. Deleting elements from a heap isn't the most elegant thing in the world, but in the grand scheme of things it's the exceptional operation here, so it shouldn't be so bad to have O(n) for this. Do you have a delete implementation we can use here?

**Comment by Simn** [comment]
Come to think of it, do we really need to remove these events from the heap in the first place? They already have a `closed` marker, so we could simply avoid executing their `func` if it's closed. This would also avoid this entire `closeClosure` business.

Doing this makes all tests pass except for `testSemaphoreTryAcquire`, which might again be related to virtual scheduler timing behavior.

**Comment by Aidan63** [comment]
Initial idea that I didn't implement was that each node in the heap would contain a linked list of closures to be executed at that time, we keep FIFO ordering of events at the same time this way, so removing an event is then removing it from the linked list.

Doing some reading it seems like an auxillary self-balancing BST is often used for this since searching a heap is O(n). I think the idea is that when adding an event to the scheduler you do a BST search of that time, and the BST stores the position of the linked list in the heap array which you can then index into. Did not get around to trying this.

**Comment by Aidan63** [comment]
I've been playing around with a combined BST and heap event loop. Idea being that each node in the heap contains a linked list of FIFO events for the given time and the BST also contains those nodes, I don't think my original thought of the BST containing indexes into the heap works because those indexes change when the heap is modified.

When a function is added to the scheduler it first tries to insert it into the BST, if there is a node with the specified time already in the BST then it will fail and return that node so we can add it to the FIFO chain of events at that time. If inserting to the BST succeeds we then also add it to the heap.

Pulling events from the scheduler is similar to before, except after we extract from the heap we need to remove the corresponding node from the BST.

This does have more lookup compared to just the minimum heap, but it does allow full FIFO ordering and the BST allows faster lookup of the scheduled events if need be. Currently I'm just using a bog standard BST instead of a self balancing one so it's probably not that great... I've also not implemented all the cancelling stuff either. I'll post it below anyway.

```haxe
package hxcoro.schedulers;

import hxcoro.ds.Out;
import haxe.Timer;
import haxe.Int64;
import haxe.coro.Mutex;
import haxe.coro.schedulers.Scheduler;
import haxe.coro.schedulers.IScheduleObject;
import haxe.coro.schedulers.ISchedulerHandle;
import haxe.exceptions.ArgumentException;

private typedef Lambda = ()->Void;

private class Event implements ISchedulerHandle {
	public final call : Lambda;
	public var next : Null<Event>;

	public function new(call:() -> Void) {
		this.call = call;
		this.next = null;
	}

	public function close() {
		//
	}
}

private class ScheduledEvent {
	public final runTime : Int64;
	public var head : Null<Event>;
	public var tail : Null<Event>;

	public function new(runTime:Int64, event:Event) {
		this.runTime = runTime;
		this.head    = event;
		this.tail    = event;
	}

	public function append(event:Event) {
		tail.next = event;
		tail = event;
	}
}

private class Node {
	public var key : ScheduledEvent;
	public var left : Null<Node>;
	public var right : Null<Node>;

	public function new(key:ScheduledEvent) {
		this.key   = key;
		this.left  = null;
		this.right = null;
	}
}

private class BinarySearchTree {
	private var root : Null<Node>;

	public function new() {
		root = null;
	}

	/**
	 * Attempts to insert and event into the BST at the specified time.
	 * @param out Contains either the newly created scheduled event on a successful insertion,
	 * or the existing scheduled event if insertion failed.
	 * @return True if the event was added, false if there was already a node in the tree at that time.
	 */
	public function tryInsert(key:Int64, event:Event, out:Out<ScheduledEvent>):Bool {
		if (null == root) {
			final o = new ScheduledEvent(key, event);

			root = new Node(o);

			out.set(o);

			return true;
		}

		var current = root;
		do
		{
			if (current.key.runTime == key) {
				out.set(current.key);

				return false;
			}

			if (current.key.runTime > key && null != current.left) {
				current = current.left;
			} else if (current.key.runTime < key && null != current.right) {
				current = current.right;
			} else {
				break;
			}
		}
		while (null != current);

		final o = new ScheduledEvent(key, event);

		out.set(o);

		if (current.key.runTime > key) {
			current.left = new Node(o);
		} else {
			current.right = new Node(o);
		}

		return true;
	}

	public function find(key:Int64):Null<ScheduledEvent> {
		if (null == root) {
			return null;
		}

		var searching = root;
		while (null != searching) {
			if (searching.key.runTime == key) {
				return searching.key;
			}

			if (key > searching.key.runTime) {
				searching = root.right;
			} else {
				searching = root.left;
			}
		}

		return null;
	}

	public function delete(key:Int64) {
		if (null == root) {
			return;
		}

		doDelete(root, key);
	}

	private function doDelete(node:Node, key:Int64) {
		if (null == node) {
			return node;
		}

		if (node.key.runTime > key) {
			node.left = doDelete(node.left, key);
		} else if (node.key.runTime < key) {
			node.right = doDelete(node.right, key);
		} else {
			if (null == node.left) {
				return node.right;
			}
			if (null == node.right) {
				return node.left;
			}

			final s = successor(node);
			node.key = s.key;
			node.right = doDelete(node.right, s.key.runTime);
		}

		return node;
	}

	private function successor(current:Node) {
		current = current.right;
		while (null != current && null != current.left) {
			current = current.left;
		}

		return current;
	}
}

private class MinimumHeap {
	final storage : Array<ScheduledEvent>;

	public function new() {
		storage = [];
	}

	public function left(i:Int) {
		return (i << 1) + 1;
	}

	public function right(i:Int) {
		return (i << 1) + 2;
	}

	public function parent(i:Int) {
		return (i - 1) >> 1;
	}

	public function minimum() {
		if (storage.length == 0) {
			return null;
		}

		return storage[0];
	}

	public function insert(event:ScheduledEvent) {
		storage.push(event);

		var i = storage.length - 1;
		while (i > 0 && storage[parent(i)].runTime > storage[i].runTime) {
			final p = parent(i);

			swap(i, p);

			i = p;
		}
	}

	public function extract() {
		if (storage.length == 0) {
			return null;
		}

		if (storage.length == 1) {
			return storage.pop();
		}

		final root = minimum();
		storage[0] = storage[storage.length - 1];
		storage.pop();

		heapify(0);

		return root;
	}

	function swap(fst:Int, snd:Int) {
		final temp = storage[fst];
		storage[fst] = storage[snd];
		storage[snd] = temp;
	}

	function heapify(index:Int) {
		while (true) {
			final l = left(index);
			final r = right(index);

			var smallest = index;
			if (l < storage.length && storage[l].runTime < storage[smallest].runTime) {
				smallest = l;
			}
			if (r < storage.length && storage[r].runTime < storage[smallest].runTime) {
				smallest = r;
			}

			if (smallest != index) {
				swap(index, smallest);
				index = smallest;
			} else {
				break;
			}
		}
	}
}

class EventLoopScheduler extends Scheduler {
	final futureMutex : Mutex;
	final heap : MinimumHeap;
	final bst : BinarySearchTree;
	final out : Out<ScheduledEvent>;

	public function new() {
		super();

		futureMutex  = new Mutex();
		heap         = new MinimumHeap();
		bst          = new BinarySearchTree();
		out          = new Out();
	}

    public function schedule(ms:Int64, func:()->Void):ISchedulerHandle {
		if (ms < 0) {
			throw new ArgumentException("Time must be greater or equal to zero");
		}

		final event = new Event(func);

		futureMutex.acquire();

		if (bst.tryInsert(ms, event, out)) {
			heap.insert(out.get());
		} else {
			out.get().append(event);
		}

		futureMutex.release();

		return event;
    }

	public function scheduleObject(obj:IScheduleObject) {
		schedule(0, obj.onSchedule);
	}

	public function now() {
		return Timer.milliseconds();
	}

	public function run() {
		final currentTime = now();

		while (true) {
			futureMutex.acquire();
			final minimum = heap.minimum();
			if (minimum == null || minimum.runTime > currentTime) {
				break;
			}

			final extracted = heap.extract();

			bst.delete(extracted.runTime);

			var e = extracted.head;
			while (null != e) {
				e.call();
		
				e = e.next;
			}

			futureMutex.release();
		}

		futureMutex.release();
	}

	public function toString() {
		return '[EventLoopScheduler]';
	}
}
```

**Comment by Simn** [comment]
That looks quite clever. I'll play around with it and see if it solves all our problems.

**Comment by Simn** [comment]
I went through the samples here again to make sure:

* https://github.com/Aidan63/haxe/issues/121#issuecomment-3696011713 doesn't hang anymore.
* https://github.com/Aidan63/haxe/issues/121#issuecomment-3694996557 runs into https://github.com/HaxeFoundation/hxcoro/issues/28, which causes poor scaling. The sample is a bit unfortunate in general though because the readers never terminate. We can make a version of it that breaks out of the readers though:

```haxe
import hxcoro.ds.channels.Channel;
import hxcoro.ds.Out;
import haxe.Timer;
import hxcoro.CoroRun;
import hxcoro.Coro.*;

function main() {
	final startTime = Timer.stamp();
	var aggregateValue = 0;
	CoroRun.runScoped(node -> {
		final channel = Channel.createBounded({size: 10});
		final numTasks = 100000;

		// set up writers
		var count = 0;
		for (_ in 0...numTasks) {
			node.async(_ -> {
				delay(Std.random(1000));

				channel.writer.write(1);

				if (++count == numTasks) {
					channel.writer.close();
				}
			});
		}

		// set up readers
		for (_ in 0...numTasks) {
			node.async(_ -> {
				final o = new Out();

				while (channel.reader.waitForRead()) {
					delay(Std.random(1000));
					if (channel.reader.tryRead(o)) {
						aggregateValue += o.get();
						break;
					} else {
						continue;
					}
				}
			});
		}

		node.awaitChildren();

		trace("done");
	});
	trace('done after ${Timer.stamp() - startTime} seconds, aggregate value is $aggregateValue');
}
```

JVM completes this in 7 seconds, which isn't great but suggests that it's not terrible. By adding some hacks to the bounded channel I can get it down to 2 seconds.
